const avatarsData = [
  {filename: 'Alex_Seven.png', name: 'Alex Seven'},
  {filename: 'Alexander_Paulsson.png', name: 'Alexander Paulsson'},
  {filename: 'Alexander_Sirotkin.png', name: 'Alexander Sirotkin'},
  {filename: 'Alexandr_Kikhtenko.png', name: 'Alexandr Kikhtenko'},
  {filename: 'Alexey_Churkin.png', name: 'Alexey Churkin'},
  {filename: 'Alexey_Goncharov.png', name: 'Alexey Goncharov'},
  {filename: 'Alexey_Ostroumov.png', name: 'Alexey Ostroumov'},
  {filename: 'Alina_Smorodova.png', name: 'Alina Smorodova'},
  {filename: 'Ann_Ark.png', name: 'Ann Ark'},
  {filename: 'Anna_Koryakova.png', name: 'Anna Koryakova'},
  {filename: 'Artem_Otvod.png', name: 'Artem Otvod'},
  {filename: 'Artem_Tkach.png', name: 'Artem Tkach'},
  {filename: 'Danil_Rusanov.png', name: 'Danil Rusanov'},
  {filename: 'Danya_Sativa.png', name: 'Danya Sativa'},
  {filename: 'Dary_Shi.png', name: 'Dary Shi'},
  {filename: 'Denis_Sankovsky.png', name: 'Denis Sankovsky'},
  {filename: 'Dimka_Sokolov.png', name: 'Dimka Sokolov'},
  {filename: 'Dmitrii_Verkhoturov.png', name: 'Dmitrii Verkhoturov'},
  {filename: 'Dmitry_Kang_BL.png', name: 'Dmitry Kang BL'},
  {filename: 'Emin_Krasna.png', name: 'Emin Krasna'},
  {filename: 'Eugene_Peacelover.png', name: 'Eugene Peacelover'},
  {filename: 'German.png', name: 'German'},
  {filename: 'Gleb_Deer.png', name: 'Gleb Deer'},
  {filename: 'Igor_Bezdetko.png', name: 'Igor Bezdetko'},
  {filename: 'Igor_Irbitskiy.png', name: 'Igor Irbitskiy'},
  {filename: 'Ilya_Danilov.png', name: 'Ilya Danilov'},
  {filename: 'Iren_Belk.png', name: 'Iren Belk'},
  {filename: 'Islam_Chagaev.png', name: 'Islam Chagaev'},
  {filename: 'Ivan_Filippsky.png', name: 'Ivan Filippsky'},
  {filename: 'Ivan_Rys.png', name: 'Ivan Rys'},
  {filename: 'Julia_Naraikina.png', name: 'Julia Naraikina'},
  {filename: 'Keran_Keran.png', name: 'Keran Keran'},
  {filename: 'Kirill_Dyakonov.png', name: 'Kirill Dyakonov'},
  {filename: 'Konstantin.png', name: 'Konstantin'},
  {filename: 'Konstantin_Kovalenko.png', name: 'Konstantin Kovalenko'},
  {filename: 'Ksenia_Aventurt.png', name: 'Ksenia Aventurt'},
  {filename: 'Lex_Lex.png', name: 'Lex Lex'},
  {filename: 'Lora_Buchatskaia.png', name: 'Lora Buchatskaia'},
  {filename: 'Maksim_Mikhaylov.png', name: 'Maksim Mikhaylov'},
  {filename: 'Maria_Semenkovskaya.png', name: 'Maria Semenkovskaya'},
  {filename: 'Marina_Kapylovich.png', name: 'Marina Kapylovich'},
  {filename: 'Max_Malyy.png', name: 'Max Malyy'},
  {filename: 'Michail_Kuznetsov.png', name: 'Michail Kuznetsov'},
  {filename: 'Misha_Dioxin.png', name: 'Misha Dioxin'},
  {filename: 'Misha_Tsvetkov.png', name: 'Misha Tsvetkov'},
  {filename: 'Mr__G.png', name: 'Mr  G'},
  {filename: 'Nikita_Bogomolov.png', name: 'Nikita Bogomolov'},
  {filename: 'Oksana_Kolomiets.png', name: 'Oksana Kolomiets'},
  {filename: 'Olga.png', name: 'Olga'},
  {filename: 'POKRAS_LAMPAS.png', name: 'POKRAS LAMPAS'},
  {filename: 'Pavel_N.png', name: 'Pavel N'},
  {filename: 'Pavel_Tumaev.png', name: 'Pavel Tumaev'},
  {filename: 'Philipp_Pavlov.png', name: 'Philipp Pavlov'},
  {filename: 'Roik_Andrey.png', name: 'Roik Andrey'},
  {filename: 'Roma_May.png', name: 'Roma May'},
  {filename: 'SantGreens.png', name: 'SantGreens'},
  {filename: 'Sergey_Nekozyrev.png', name: 'Sergey Nekozyrev'},
  {filename: 'Sovka_Ivanov.png', name: 'Sovka Ivanov'},
  {filename: 'Svyatoslav_Dengin__INT.png', name: 'Svyatoslav Dengin  INT'},
  {filename: 'Timur_Malygin.png', name: 'Timur Malygin'},
  {filename: 'UR.png', name: 'UR'},
  {filename: 'V.png', name: 'V'},
  {filename: 'Victor.png', name: 'Victor'},
  {filename: 'Victoria_Malova.png', name: 'Victoria Malova'},
  {filename: 'Vladimir_Tanay.png', name: 'Vladimir Tanay'},
  {filename: 'Whisp.png', name: 'Whisp'},
  {filename: 'Yulia_Nesterova.png', name: 'Yulia Nesterova'},
  {filename: 'Yuriy_Kubickiy.png', name: 'Yuriy Kubickiy'},
  {filename: 'anya_krolya.png', name: 'anya krolya'},
  {filename: 'imortl_ID.png', name: 'imortl ID'},
  {filename: 'letiz.png', name: 'letiz'},
  {filename: 'yalhis_desu.png', name: 'yalhis desu'},
  {filename: 'Александра_Дубинина.png', name: 'Александра Дубинина'},
  {filename: 'Андрей.png', name: 'Андрей'},
  {filename: 'Андрей_Мельников.png', name: 'Андрей Мельников'},
  {filename: 'Артур_Устименко__Aust917.png', name: 'Артур Устименко  Aust917'},
  {filename: 'Вадим_Данилков.png', name: 'Вадим Данилков'},
  {filename: 'Влад_Соловьёв.png', name: 'Влад Соловьёв'},
  {filename: 'Джон_Три_дэшник.png', name: 'Джон Три дэшник'},
  {filename: 'Евгений_Астраханцев.png', name: 'Евгений Астраханцев'},
  {filename: 'Евгений_Мишунин__Моушн_дизайнер_маркетолог.png', name: 'Евгений Мишунин  Моушн дизайнер маркетолог'},
  {filename: 'Женя_Дружинин.png', name: 'Женя Дружинин'},
  {filename: 'Иван_Волощук.png', name: 'Иван Волощук'},
  {filename: 'Настя_Яценко.png', name: 'Настя Яценко'},
  {filename: 'Роман.png', name: 'Роман'},
  {filename: 'Рустам_Аразов.png', name: 'Рустам Аразов'},
  {filename: 'Саша.png', name: 'Саша'},
  {filename: 'Саша_Потехин.png', name: 'Саша Потехин'},
  {filename: 'Семён_Павлов.png', name: 'Семён Павлов'},
  {filename: 'Сергей_Маслов.png', name: 'Сергей Маслов'},
  {filename: 'Стас_Третьяк.png', name: 'Стас Третьяк'},
  {filename: 'Тимур_Ибрагимов.png', name: 'Тимур Ибрагимов'},
  {filename: 'Шамиль_Тарба.png', name: 'Шамиль Тарба'},
  {filename: 'Ярослав_Беспалов.png', name: 'Ярослав Беспалов'},
  {filename: 'Ярослав.png', name: 'Ярослав'},
];
